### ISSUE TITLE
Adding GroupLayers causes PSD to fail

### ISSUE THREAD

**Issue by Gofven** [EmilDohne/PhotoshopAPI#111]
This happens when there's group layers present in LayeredFile_8bit class. I've looked around for any cues and found out all GroupLayer classes (8bit, 16bit and 32bit) are missing a "self" parameter in their __init__ method.

Although I did try to manually add this myself, it seemed to still cause issues, I'm willing to provide more information, although due to how much this script I've written relies on external sources, it'll require a bit of time, but I wouldn't mind c:

Also note that I've only attempted to open the psd's created using Krita/FireAlpaca, I don't have any PS license available unfortunately

If anyone wants to give it a quick read, you here's a hastebin available c:
https://hastebin.com/share/ivuzehozit.scss

**Comment by EmilDohne** [comment]
Hey @Gofven, I had a look and figured out why krita doesn't like these file. 

Krita appears to expect the group layers to have empty channels even if no channels are present (just zero length) which Photoshop does itself actually write out but doesn't require (unlike krita). Seems like I even thought about that at the time of writing.

```cpp
0u, // Number of channels, photoshop does appear to actually write out all the channels with 0 length, we will see later if that is a requirement
```

As for the constructor not taking self that's just an error on my side in the stubs, I've created a ticket to address that: #112 

I'll get a fix pushed soon and then you can grab the updated wheel from the CI directly until the next release comes out. Thanks for the flag!

**Comment by EmilDohne** [comment]
I've merged this now and you can grab the update wheels (until the next release comes out) from [here](https://github.com/EmilDohne/PhotoshopAPI/actions/runs/11232582368), at the bottom you will see a `PhotoshopAPI_Py` zipfile which will have all the wheels.

I plan on releasing `0.5.0` fairly soon (this or next week depending on complexity) so until then you could have a `bin` directory in your repo which contains the wheel until 0.5.0 is out including these changes :)

To then install them simply run: 
`py -m pip install PhotoshopAPI-0.4.0-cp311-cp311-win_amd64.whl` <-- Replace this with your py version

making sure to first 
`py -m pip uninstall photoshopapi`

Keep in mind that I added a check that no longer allows you to specify a width and height on a `psapi.GroupLayer_*bit` if you dont have a mask specified so you can just leave those fields blank :)

**Comment by EmilDohne** [comment]
As for FireAlpaca, it doesnt seem to support `ZIP` compression in its internal parser, only `RLE` compression. If you want to write FireAlpaca64 compliant psd files you have to unfortunately use `RLE` which is larger in size like this:

```py
# Set RLE compression on all layers of the file
layered_file.compression = psapi.enum.Compression.rle
layered_file.write(Path(os.path.join(str(export_path), f"{texture_set}.psd")))
```

**Comment by Gofven** [comment]
I've looked through all your comments and installed the wheel provided, it works!
Also setting the compression to rle seemed to solve the issue with FireAlpaca!

Thank you so much for the quick response and solution you provided! I look forward to the upcoming release c:

**Comment by EmilDohne** [comment]
No problem, thanks for reporting!

**Comment by EmilDohne** [comment]
Hey @Gofven, just wanted to let you know that v0.5.0 is out now so you can just `pip install PhotoshopAPI` again. Do note that there was some breaking changes on the python side
