### ISSUE TITLE
Add Unicode layer name support

### ISSUE THREAD

**Issue by EmilDohne** [EmilDohne/PhotoshopAPI#82]
Currently when reading a photoshop file we only parse the ascii layer name representation which is the layer name stored on the layer records.

There is however also the `luni` Tagged block which would add support for unicode layer names.

The behaviour should then be that the layer name always chooses the unicode name (if available) and otherwise defaults to the Pascal String ascii version.

Both of these layer names should be retrievable if wanted though through a function like

`Layer<T>::getUnicodeLayerName()` and `Layer<T>::getASCIILayerName()`

**Comment by kkgg0521** [comment]
你好 我切换了PSD 大小 这样 ， 但是 他只是把psd 的画板改小了 没有把里面图层的效果改小
                 psd = psapi.LayeredFile.read(OnePs)
                    psd.width = 500
                    psd.height =500
                
                       psd.write(OnePs)
