### ISSUE TITLE
Color Channel Misalignment: Corrupted PSD Output from 16-bit PNG and 32-bit exr Conversion

### ISSUE THREAD

**Issue by binatheis** [EmilDohne/PhotoshopAPI#97]
I encountered a significant issue when using the PhotoshopAPI to convert both a 16-bit PNG image and a 32-bit multilayered EXR image to PSD files. In both cases, the resulting PSDs appear corrupted, displaying heavily distorted images that look nothing like the original files. The pixels seem misaligned or "glitched," likely due to an incorrect handling of the color depth during the conversion process.

Here's what I did:

1. Loaded a 16-bit PNG and a 32-bit EXR image using the Python Binding of the PhotoshopAPI.
2. Converted each of these formats to PSD using the API.

The resulting 2 PSD files, however, contain visual artifacts and distorted colors, indicating a possible misinterpretation of the color depth by the API. I'm sure the problem is on my end and not the API's, however, I'm putting it out there to see if I can find some sort of solution, since you administer it and the documentation doesn't go into any of these issues in depth. I'm attaching how the image look like and the PSDs where I got it (https://we.tl/t-EtqRQ7QkQ7). 
![solitaria](https://github.com/user-attachments/assets/0b07d23c-f70b-4d84-891d-682ac2ddd2a7)

**Comment by EmilDohne** [comment]
Hey @binatheis , thanks for the report! Could you outline how youre loading the png and exrs since the PhotoshopAPI doesnt expose functionality for this?

My guess is that youre using something like OpenCV which stores the images in BGR order and with the dimensions flipped. I've pushed some changes to address these issues and warn users better but if youre using the pip installed version the changes arent in there yet.

In any case maybe this discussion could provide the answer? Let me know if that does it or if its something else :)

**Comment by binatheis** [comment]
Thank you for your quick response. I appreciate your insights. Exactly, I am using the Python wheel which is in PyPI. I'm using it inside Blender 4.2 together with a script. Let me provide more details about how I'm handling the image loading and processing in my code.

### For PNG and Other Non-EXR Formats:

1. I'm using PIL (Python Imaging Library) to open the images:

    ```python
    with Image.open(file_path) as img:
        # Convert image to RGB mode if it's not already
        if img.mode != 'RGB':
            img = img.convert('RGB')
        
        # Convert image data to numpy array
        image_data = np.array(img)
    ```

2. The image data is then converted to a numpy array:

    ```python
    image_data = np.array(img)
    ```

3. Depending on the color depth, I create the PSD layer using `psapi`:

    ```python
    if color_depth == '8':
        img_layer = psapi.ImageLayer_8bit(
            image_data.transpose(2, 0, 1),
            layer_name,
            width=width,
            height=height,
            color_mode=color_mode
        )
    elif color_depth == '16':
        img_layer = psapi.ImageLayer_16bit(
            (image_data.astype(np.float32) / 255 * 65535).astype(np.uint16).transpose(2, 0, 1),
            layer_name,
            width=width,
            height=height,
            color_mode=color_mode
        )
    elif color_depth == '32':
        img_layer = psapi.ImageLayer_32bit(
            (image_data.astype(np.float32) / 255).transpose(2, 0, 1),
            layer_name,
            width=width,
            height=height,
            color_mode=color_mode
        )
    ```

### For EXR Files:

1. I'm using OpenEXR to open and read the file:

    ```python
    exr = OpenEXR.InputFile(exr_file)
    header = exr.header()
    print("EXR file opened successfully")
    print(f"EXR header: {header}")
    ```

2. I process each layer of the EXR file:

    ```python
    for layer_name, channels in layer_channels.items():
        print(f"Processing layer: {layer_name}")
        channel_data = []
        for channel in channels:
            full_channel_name = f"{layer_name}.{channel}"
            pixel_type = Imath.PixelType(Imath.PixelType.FLOAT if bit_depth == 32 else Imath.PixelType.HALF)
            channel_str = exr.channel(full_channel_name, pixel_type)
            channel_array = np.frombuffer(channel_str, dtype=np.float32 if bit_depth == 32 else np.float16).reshape(height, width)
            channel_data.append(channel_array)
    ```

3. I ensure the layer data has 3 channels (RGB):

    ```python
    if layer_data.shape[2] == 1:
        layer_data = np.repeat(layer_data, 3, axis=2)
    elif layer_data.shape[2] == 4:
        layer_data = layer_data[:,:,:3]
    elif layer_data.shape[2] != 3:
        print(f"Warning: Unsupported channel count {layer_data.shape[2]} for layer {layer_name}. Skipping.")
        continue
    ```

4. Finally, I create the PSD layer using `psapi`:

    ```python
    ImageLayer = psapi.ImageLayer_32bit if bit_depth == 32 else psapi.ImageLayer_16bit
    img_layer = ImageLayer(
        layer_data.transpose(2, 0, 1),
        create_file_safe_name(layer_name),
        width=width,
        height=height,
        color_mode=color_mode
    )
    psd_document.add_layer(img_layer)
    ```

### Question:
In both cases, I'm using `transpose(2, 0, 1)` when creating the PSD layer. Could this be causing the issue you mentioned about dimensions being flipped?

I'm not using OpenCV, so the BGR order shouldn't be a problem. However, I'm wondering if there might be an issue with how I'm handling the color depths or the normalization of the data.

Could you please take a look at these snippets and let me know if you spot any potential issues that might cause the color channel misalignment? I'd be happy to provide any additional information or make adjustments to the code based on your recommendations.

Thank you for your help!

**Comment by EmilDohne** [comment]
Hey @binatheis , this is due to np.transpose() not actually modifying the data but only changing the internal stride. to actually get this working properly you need to add copy() to the end. So np.transpose(2, 0, 1).copy(). I already pushed a change for this but this hasnt been release to pypi yet :)

**Comment by binatheis** [comment]
Ohh thank you very much Emil, we hope, then, to have everything for PhotoshopAPI 0.5.0

**Comment by EmilDohne** [comment]
No worries, I hope to get back to developing the psapi soon as I've been primarily busy with this project as of late

https://emildohne.com/imagestacker

**Comment by binatheis** [comment]
Wow! beautiful project. I would love to be able to support you on that one and also this PhotoshopAPI one by buying you a coffee at Ko-fi, ajaajaja. I have sent you the request on LinkedIn, I have a relatively large project(startup idea) that is in the Product Discovery phase and I would love to know if you would like to be part of it in the near future.

**Comment by EmilDohne** [comment]
Thanks! Im not sure if id have time to jmp on something else at the moment as im pretty full but feel free to reach out anyways. I dont think I've gotten your request yet. Have you sent it to this [account](https://www.linkedin.com/in/emildohne/)?

**Comment by binatheis** [comment]
Yes, you have accepted me. I understand, however, the project is long term and, therefore, it is by no means finished. I put a maximum of three months to finish its first phases, when we have that, after that I will present you a concrete proposal through a pitch deck so that you can consider being part of it as a founding technical and shareholder partner. Greetings from Colombia!

**Comment by EmilDohne** [comment]
Greetings back! Let me know once youre ready :)
